### ISSUE TITLE
v4.0 "CanLog" and asmdef file name

### ISSUE THREAD

**Issue by AldeRoberge** [FirstGearGames/Bayou#11]
In Bayou.cs, you have two references to "**CanLog**" : 
 if (base.NetworkManager.CanLog(LoggingType.Warning))

But that is now an internal method.

Then, **Bayou.asmdef** should be named FishNet.Bayou.Runtime, to be consistent with other asmdef files (FishNet.Runtime)

**Comment by FirstGearGames** [comment]
V4 is not stable yet, transport updates are going to be a little behind
until that happens.

**Comment by FirstGearGames** [comment]
V4 has been stable for awhile. This is no longer applicable.
