### ISSUE TITLE
Connection not starting when Bayou added at runtime

### ISSUE THREAD

**Issue by HajiyevEl** [FirstGearGames/Bayou#14]
Connection not starting when Bayou added at runtime.

<details><summary>Details</summary>
<p>

![Screenshot 2024-06-18 172635](https://github.com/FirstGearGames/Bayou/assets/70325881/73b07cb6-cd6e-427f-8a79-c082a4960928)
![Screenshot 2024-06-18 172601](https://github.com/FirstGearGames/Bayou/assets/70325881/0f3f942d-be15-4b7d-95c7-1c8f99a52883)
![Screenshot 2024-06-18 172743](https://github.com/FirstGearGames/Bayou/assets/70325881/9dd64ac9-f8b1-4a60-ba3e-b96b4b328b3c)

</p>
</details>

**Comment by FirstGearGames** [comment]
Added at runtime as in added to the Transports list inside Multipass at runtime?

**Comment by HajiyevEl** [comment]
> Added at runtime as in added to the Transports list inside Multipass at runtime?

Yes

**Comment by FirstGearGames** [comment]
This is more likely Multipass not initializing the transport after you're adding it. Looking at the multipass code it looks as though there was never intent to allow adding at runtime; if there was it's definitely not complete.

At this time adding runtime transports is not supported; I'm going to have to mark this as wont fix.

**Comment by HajiyevEl** [comment]
> At this time adding runtime transports is not supported;
Thank you for information.
