### ISSUE TITLE
Intermittently this message and error will show up using just the example authenticator and bayou .

### ISSUE THREAD

**Issue by bitmammoth** [FirstGearGames/Bayou#4]
To trigger the error open the example then assign bayou to the transport manager, start the server and then connect a client/disconnect when successful. Repeat that process and every so often that will pop up. It showed first back at 2.6.6 (wasn't sure how to repro it in my main project) but currently I am running 3.1.1pro. This only happens with Bayou as far as I can tell, that or I am doing something wrong .
![image](https://user-images.githubusercontent.com/21980039/211673057-3c168f04-e594-4864-849a-cd0891d17659.png)

**Comment by FirstGearGames** [comment]
Thank I'll see what could be going on.

**Comment by bitmammoth** [comment]
here is the error without the debugging lines :
NullReferenceException: Object reference not set to an instance of an object
FishNet.Managing.Server.ServerManager.ParseReceived (FishNet.Transporting.ServerReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:544)
FishNet.Managing.Server.ServerManager.Transport_OnServerReceivedData (FishNet.Transporting.ServerReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Server/ServerManager.cs:458)

**Comment by bitmammoth** [comment]
Closing this for now as it seems to be no longer an issue, will reopen if needed.
