### ISSUE TITLE
SendLoop crashing because writeBuffer too small (Happens with large number of synchronized objects)

### ISSUE THREAD

**Issue by CryShana** [FirstGearGames/Bayou#5]
I have been encountering random server connection crashes while using this Transport and I decided to quickly check it out myself as I needed a quick fix. I created this issue to simply bring attention to this bug.

### The problem
(I'm using the latest 2.0.0 release)

This seems to happen when there are a lot of objects in-scene that need to be synchronized. Because I spawn new objects as the game progresses, this crash happens only later on when there are sufficient objects in the scene, not immediately.

When it eventually happens, every connection SendLoop will crash at the same time with the following exception being thrown: 

(this screenshot was taken when I had **5 connected players** - you can see an error for each player)
![image](https://user-images.githubusercontent.com/951230/211877414-1950c5fe-9854-4de5-ad74-72b83cb67fde.png)

The error happens in `SendLoop.cs:100` at the following line: (because the `writeBuffer` is too small to receive the `msg`)
```cs
int length = SendMessage(writeBuffer, 0, msg, setMask, maskHelper);
```
Inside of which we call the `msg.CopyTo(...)` at `SendLoop.cs:134` that causes the crash.

Here is the relevant function: (I added my own comments from my debugging session)
```cs
static int SendMessage(byte[] buffer, int startOffset, ArrayBuffer msg, bool setMask, MaskHelper maskHelper)
{
    int msgLength = msg.count;
    int offset = WriteHeader(buffer, startOffset, msgLength, setMask);

    if (setMask)
    {
        offset = maskHelper.WriteMask(buffer, offset);
    }

    // CRASHES HERE - values were as follows:
    // [msg] was 1024 in size
    // [buffer] was 1027 in size,
    // [offset] was 4
    msg.CopyTo(buffer, offset);
    offset += msgLength;
```
If I subtract the offset, the resulting buffer is 1023 in size - which is 1 byte too shy from the 1024-sized msg. Coincidentally my MTU setting is also 1023, which sets the `buffer` size - so this makes sense. So I assumed this means the `msg` ArrayBuffer was 1 byte too large and continued to dig deeper.

The ArrayBuffer gets enqueued at `WebSocketServer.cs:221`, which gets the data from `SimpleWebServer.cs:72`, which gets data from `ServerSocket.cs:298`, which is this part:
```cs
for (int i = 0; i < count; i++)
{
    Packet outgoing = _outgoing.Dequeue();
    int connectionId = outgoing.ConnectionId;
    AddChannel(ref outgoing); // <--- this is where the extra byte gets added

    // this is where the large segment is created that gets enqueued later
    ArraySegment<byte> segment = outgoing.GetArraySegment()
}
```
And I found the culprit, the `AddChannel(ref outgoing)` adds the 1 extra byte that makes it too large.

Given that we need that channel data, means that either the `Packet` itself should've been created with that extra byte in mind or the buffer in the Transport. So I dug further again. The relevant ArraySegment seems to be created at `TransportManager.cs:404` with the following line:
```cs
ArraySegment<byte> segment = new ArraySegment<byte>(bb.Data, 0, bb.Length)
```
This already takes me outside of Bayou into Fishnet runtime.

The buffers are created in `Buffer.cs` and they use the MTU setting to set the size. Relevant line below:
```cs
ByteBuffer ba = new ByteBuffer(_maximumTransportUnit, _reserve);
```

### Conclusion
I finally learn that both buffers get created with the MTU setting. The problem occurs when the outgoing buffer gets increased by 1 byte to hold the channel data but the destination buffer doesn't.

### The hotfix

I went back to `SendLoop.cs:45` and adjusted the allocation to this:
```cs
byte[] writeBuffer = new byte[bufferSize + 1]; // +1 for channel byte
```
This fixed the issue for me.

I didn't create any pull requests or whatever because this was a really quick fix and I didn't have time to test it thoroughly. But I hope you can properly review and fix this issue in the future.

**Comment by FirstGearGames** [comment]
Nice find. Several transports use the byte because not all platforms
specify incoming channel. I'll make the changes internally.

**Comment by FirstGearGames** [comment]
This was changed in current development branch. Transport will still initialize it's buffer on it's specified MTU is applicable but FishNet reserves 1 byte for it's buffers. So if you use transportManager.GetMTU() it will the adjusted MTU.
