### ISSUE TITLE
Please add an asmdef!

### ISSUE THREAD

**Issue by celojevic** [FirstGearGames/Bayou#6]
Ive made my own but it'd help if i didnt need to!

The SimpleWebTransport asmdef is not enough to access Bayou from another assembly

**Comment by dh-hathora** [comment]
+1, experiencing the same conflicts

**Comment by dh-hathora** [comment]
Any word on this?

**Comment by FirstGearGames** [comment]
I will add an asmdef soon as I'm able to get back on schedule with things.

**Comment by FirstGearGames** [comment]
Added
