### ISSUE TITLE
Default path should be changed

### ISSUE THREAD

**Issue by dh-hathora** [FirstGearGames/Bayou#8]
![image](https://github.com/FirstGearGames/Bayou/assets/135207109/e95debac-9ba3-4814-b852-00d9232a9f21)

To conform with FishNet's layout and prevent confusion if this doesn't require being in a Unity-reserved /Plugins dir, this probably shouldn't be `FishNet/Plugins/`, but `FishNet/Runtime/Transporting/Transports/` to be a sibling of the other transports.

Unless there's something that actually needs to be compiled to a Unity /Plugins/ dir? I was able to run it fine (tested with WSS TLS) without being in a /Plugins dir

**Comment by FirstGearGames** [comment]
Most likely going to do a path reform on some things in v4 release. I'd
like to keep things that have to be manually imported in the plug-ins
folder and default components under Runtime.

The idea would be if someone had to wipe their FishNet folder they could
just move out the plug-ins before deleting, or simply restore via git after
wipe.

**Comment by FirstGearGames** [comment]
Changed in v4
