### ISSUE TITLE
Error- 'ListCache<>'  NameSpace not present - Version 4+

### ISSUE THREAD

**Issue by DylanKontos** [FirstGearGames/Bayou#9]
Version 4.0.2 and 4.0.0 - I'm getting an assembly reference error:

The type or namespace name 'ListCache<>' could not be found (are you missing a using directive or an assembly reference?)[CS0246](https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS0246%29)

Does not occur with previous versions.

Thanks!

**Comment by FirstGearGames** [comment]
Yeah, it's removed in v4 and replaced with CollectionCaches<>.RetrieveList. Later versions of 3 also have CollectionCaches.

**Comment by FirstGearGames** [comment]
I just merged a PR for this which will fix the issue for v3 and v4. You will see it pop up on the releases soon as well.
